config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  resources 'tweets'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :message, presence: true
  validates :message, length:{maximum:140}
  
  def hello2
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
    logger.debug "こちらはapplication_controllerですぅ＞－＜"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
    hello
    Tweet.new.hello2
    logger.debug "tweets_controllerです^q^"
  end
  def new
    @tweet = Tweet.new
  end
  def create
    @tweet = Tweet.new(message:params[:tweet][:message], tdate:Time.current)
    if @tweet.save
      
      redirect_to '/'
    else
      render 'new'
    end
  end
  def destroy
    tweet = Tweet.find(params[:id])
      tweet.destroy
      redirect_to '/'
  end
  def show
    @tweet = Tweet.find(params[:id])
  end
  def edit
    @tweet = Tweet.find(params[:id])
  end
  def update
    tweet = Tweet.find(params[:id])
    tweet.update(message:params[:tweet][:message], tdate:Time.current)
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="container">
    <div id="header">
      <%= render "header" %>
    </div>
    <div id="sideber">
      <%= render "sideber" %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
    <div id="footer">
      <%= render "footer" %>
    </div>
  </div>
</body>

</html>

app/views/tweets/_form.html.erb
<%= f.label :message, 'メッセージ' %><br>
<%= f.text_area :message, rows: 5, cols: 60 %>
<%= f.submit 'ツイート' %>

app/views/tweets/_header.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <link href="_header.css" type="text/css" rel="stylesheet">
</head>

<body background-color: #FFFFFF>
  <p class="btn"><%= link_to ' Tweet ',new_tweet_path %></p>
  <img class="imgform" src="/kindai.jpg">

    <div id="pagetitle">
      <img class="imgprof" src="/a.PNG">
      <img class="imgpro" src="/kindai.jpg">
      <div id="pagefollowers">
        Tweets　　　following　　　followers　　　likes<br><br>
      </div>
    </div>
</body>

</html>

app/views/tweets/_sideber.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <link href="index.css" type="text/css" rel="stylesheet">
</head>

<body><br><br>
  <div id="pageproname">
    　   近畿大学
    　   <div id="pageaka">
    　     　@kinkidaigakuPR<br><br>
        </div>
  </div>
  <div id="pageprokome">
      　　近畿大学総務部広報室のTwitter公式アカ<br>
      　　ウントです。近畿大学ホームページの更<br>
      　　新情報を中心に、大学に関する情報を発信<br>
      　　していきます。 個別DMでのお問い合わせ<br>
      　　には返信を行っておりませんので、ご了承<br>
      　　ください。
  </div>
</body>

</html>

app/views/tweets/edit.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <link href="show.css" type="text/css" rel="stylesheet">
</head>

<body>
  <div id="showbody">
    <div id="showtweet">
      <%= form_for @tweet, url:{action: :update} do |f| %>
      <%= render "form", f: f %>
      <% end %>
      <%= link_to 'Back', '/' %>
    </div>
  </div>
</body>
</html>

app/views/tweets/index.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <link href="index.css" type="text/css" rel="stylesheet">
</head>
  
<body>
    <% flash.each do |type, msg| %>
      <%= msg %>
    <% end %>


    <br><div id="pagetweet">
      <h2>Tweets</h2>
      <% @tweets.each do |tweet| %>
        <p>
          <%= link_to tweet.message, tweet%>
          <%= (Time.current - tweet.tdate).to_i / 60 %>分前<br>
          <%= link_to '削除', tweet, method: :delete %>
          <%= link_to '編集', edit_tweet_path(tweet) %><hr>
        </p>
      <% end %>
    </div>
</body>

</html>

app/views/tweets/new.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <link href="show.css" type="text/css" rel="stylesheet">
</head>

<body>
  <div id="showbody">
    <div id="showtweet">
<% if @tweet.errors.present? %>
<h3>エラーです。</h3>
<ul>
  <% @tweet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @tweet, url:{action: :create} do |f| %>
  <%= render "form", f: f %>
<% end %>
    </div>
  </div>
</body>
</html>

app/views/tweets/show.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <link href="show.css" type="text/css" rel="stylesheet">
</head>

<body>
  <div id="showbody">
    <div id="showtweet">
<p>
  <strong>メッセージ：</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>経過時間：</strong>
  <%= (Time.current - @tweet.tdate).to_i / 60 %>分前
</p>

<%= link_to 'Back', '/' %>
    </div>
  </div>
</body>
</html>